# Generated by Django 5.2.4 on 2025-07-21 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('forma_pagamento', models.CharField(max_length=100)),
                ('status_pagamento', models.CharField(max_length=100)),
                ('status_agendamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=100)),
                ('email_paciente', models.EmailField(max_length=254)),
                ('whatsapp_paciente', models.CharField(max_length=30)),
                ('senha_paciente', models.CharField(max_length=30)),
                ('cpf_paciente', models.CharField(max_length=30)),
                ('data_nascimento', models.DateField()),
                ('observacoes_sintomas', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_profissional', models.CharField(max_length=100)),
                ('email_profissional', models.EmailField(max_length=254)),
                ('whatsapp_profissional', models.CharField(max_length=30)),
                ('senha_profissional', models.CharField(max_length=30)),
                ('cpf_profissional', models.CharField(max_length=30)),
                ('data_nascimento', models.DateField()),
                ('especializacoes', models.CharField(max_length=200)),
                ('crm', models.CharField(max_length=30, null=True)),
                ('status_aprovacao', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Comprovante_pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_agendamento', models.CharField(max_length=100)),
                ('agendamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.agendamento')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.CharField(max_length=100)),
                ('prescricao', models.CharField(max_length=100)),
                ('observacoes_consulta', models.CharField(max_length=100)),
                ('agendamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.agendamento')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem_WPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mensagem', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=100)),
                ('data_envio', models.DateTimeField()),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='paciente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.paciente'),
        ),
        migrations.CreateModel(
            name='horario_disponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField()),
                ('profissional_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.profissional')),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='profissional_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.profissional'),
        ),
        migrations.CreateModel(
            name='Receita_medica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.CharField(max_length=100)),
                ('prescricao', models.CharField(max_length=100)),
                ('consulta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.consulta')),
            ],
        ),
    ]
