# Generated by Django 5.2.4 on 2025-07-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='observacoes_sintomas',
        ),
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes/fotos/'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_paciente',
            field=models.CharField(max_length=200),
        ),
    ]
