# Generated by Django 5.2.6 on 2025-09-16 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_availability_professional_appointment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='email_paciente',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='nome_paciente',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='senha_paciente',
            new_name='senha',
        ),
    ]
