# Generated by Django 5.2.6 on 2025-09-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_rename_email_paciente_paciente_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='agendamento_id',
        ),
        migrations.RemoveField(
            model_name='receita_medica',
            name='consulta_id',
        ),
        migrations.RemoveField(
            model_name='mensagem_wpp',
            name='paciente_id',
        ),
        migrations.AddField(
            model_name='profissional',
            name='foto_profissional',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes/fotos/'),
        ),
        migrations.DeleteModel(
            name='Comprovante_pagamento',
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.DeleteModel(
            name='Receita_medica',
        ),
        migrations.DeleteModel(
            name='Mensagem_WPP',
        ),
    ]
