# Generated by Django 5.2.6 on 2025-11-04 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_horariodisponivel_delete_vagaemprego'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='horariodisponivel',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Disponível'),
        ),
        migrations.AlterField(
            model_name='horariodisponivel',
            name='data',
            field=models.DateField(verbose_name='Data do Atendimento'),
        ),
        migrations.AlterField(
            model_name='horariodisponivel',
            name='hora_fim',
            field=models.TimeField(verbose_name='Hora de Término'),
        ),
        migrations.AlterField(
            model_name='horariodisponivel',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Hora de Início'),
        ),
        migrations.AlterField(
            model_name='horariodisponivel',
            name='profissional',
            field=models.ForeignKey(limit_choices_to={'is_professional': True}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disponiveis', to=settings.AUTH_USER_MODEL),
        ),
    ]
