# Generated by Django 5.2.6 on 2025-11-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_agendamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agendamento',
        ),
    ]
