# Generated by Django 5.2.6 on 2025-10-10 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_horariodisponivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariodisponivel',
            name='profissional',
            field=models.ForeignKey(limit_choices_to={'is_professional': True}, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_horarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
