# Generated by Django 5.2.6 on 2025-10-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_horariodisponivel_profissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioadaptado',
            name='biografia',
            field=models.TextField(blank=True, null=True, verbose_name='Biografia'),
        ),
        migrations.AddField(
            model_name='usuarioadaptado',
            name='crm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CRM'),
        ),
        migrations.AddField(
            model_name='usuarioadaptado',
            name='email_profissional',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Profissional'),
        ),
        migrations.AddField(
            model_name='usuarioadaptado',
            name='especializacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Especialização'),
        ),
        migrations.AddField(
            model_name='usuarioadaptado',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Contato'),
        ),
    ]
