# Generated by Django 5.2.6 on 2025-11-04 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuarioadaptado_biografia_usuarioadaptado_crm_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HorarioDisponivel',
        ),
    ]
