# Generated by Django 5.2.6 on 2025-11-04 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_delete_horariodisponivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do Atendimento')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de Término')),
                ('ativo', models.BooleanField(default=True, verbose_name='Disponível')),
                ('profissional', models.ForeignKey(limit_choices_to={'is_professional': True}, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_horarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horário Disponível',
                'verbose_name_plural': 'Horários Disponíveis',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
    ]
