# Generated by Django 5.2.6 on 2025-11-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_agendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariodisponivel',
            name='profissional',
        ),
        migrations.DeleteModel(
            name='Agendamento',
        ),
        migrations.DeleteModel(
            name='HorarioDisponivel',
        ),
    ]
