# Generated by Django 5.2.6 on 2025-11-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_agendamento_horariodisponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='concluida',
            field=models.BooleanField(default=False, verbose_name='Consulta Concluída'),
        ),
    ]
