# Generated by Django 5.2.6 on 2025-11-11 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_agendamento_concluida'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoCancelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('mensagem', models.CharField(max_length=255)),
                ('lido', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_cancelamento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
